#!/usr/bin/env node
import { spawnSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const repoRoot = resolve(__dirname, '..');
const workspaceRoot = resolve(repoRoot, '..');
const themesDir = resolve(workspaceRoot, 'bitsandbolts-themes');
const themesRepoUrl = 'https://github.com/bitsandbolts/bitsandbolts-themes.git';

const VALID_DEFAULTS = new Set(['system', 'light', 'dark']);

function fail(msg) {
  console.error(msg);
  process.exit(1);
}

function run(command, args, options = {}) {
  const proc = spawnSync(command, args, {
    stdio: 'inherit',
    ...options,
  });
  if (proc.status !== 0) {
    fail(`Command failed: ${command} ${args.join(' ')}`);
  }
}

function parseArgs(argv) {
  const opts = {
    theme: '',
    defaultMode: 'dark',
  };

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--theme') {
      opts.theme = argv[i + 1] ?? '';
      i += 1;
      continue;
    }
    if (arg === '--default') {
      opts.defaultMode = (argv[i + 1] ?? '').toLowerCase();
      i += 1;
      continue;
    }
    if (arg === '--help' || arg === '-h') {
      console.log('Usage: pnpm change-theme --theme <name> [--default system|light|dark]');
      process.exit(0);
    }
    fail(`Unknown arg: ${arg}`);
  }

  if (!opts.theme) fail('Missing required --theme <name>');
  if (!VALID_DEFAULTS.has(opts.defaultMode)) {
    fail(`Invalid --default value: ${opts.defaultMode}. Use one of: system, light, dark`);
  }

  return opts;
}

function ensureThemesRepo() {
  if (!existsSync(themesDir)) {
    console.log(`[theme] bitsandbolts-themes not found at ${themesDir}. Cloning...`);
    run('git', ['clone', themesRepoUrl, themesDir]);
  }

  console.log('[theme] Pulling latest bitsandbolts-themes...');
  run('git', ['-C', themesDir, 'fetch', '--all', '--prune']);
  run('git', ['-C', themesDir, 'pull', '--ff-only']);

  console.log('[theme] Building bitsandbolts-themes...');
  run('pnpm', ['install', '--frozen-lockfile'], { cwd: themesDir });
  run('pnpm', ['build'], { cwd: themesDir });
}

function copyWebTheme(theme, defaultMode) {
  const srcThemeDir = join(themesDir, 'dist', 'web', theme);
  if (!existsSync(join(srcThemeDir, 'light.css'))) {
    fail(`Theme not found in dist/web: ${theme}`);
  }

  const outDir = join(repoRoot, 'src', 'styles', 'theme-generated');
  mkdirSync(outDir, { recursive: true });

  cpSync(join(srcThemeDir, 'light.css'), join(outDir, 'light.css'));
  cpSync(join(srcThemeDir, 'dark.css'), join(outDir, 'dark.css'));
  cpSync(join(srcThemeDir, 'icons.css'), join(outDir, 'icons.css'));

  const componentsSrc = join(themesDir, 'dist', 'web', 'components');
  const componentsDst = join(outDir, 'components');
  rmSync(componentsDst, { recursive: true, force: true });
  mkdirSync(componentsDst, { recursive: true });
  for (const file of readdirSync(componentsSrc)) {
    if (file.endsWith('.css')) {
      cpSync(join(componentsSrc, file), join(componentsDst, file));
    }
  }

  const iconsSrc = join(themesDir, 'dist', 'web', 'icons');
  const iconsDst = join(outDir, 'icons');
  rmSync(iconsDst, { recursive: true, force: true });
  mkdirSync(iconsDst, { recursive: true });
  for (const file of readdirSync(iconsSrc)) {
    if (file.endsWith('.svg')) {
      cpSync(join(iconsSrc, file), join(iconsDst, file));
    }
  }

  const defaultsFile = join(repoRoot, 'src', 'generated', 'themeDefaults.ts');
  mkdirSync(dirname(defaultsFile), { recursive: true });
  writeFileSync(
    defaultsFile,
    [
      '// Auto-generated by scripts/change-theme.mjs — do not edit.',
      `export const THEME_NAME = '${theme}' as const;`,
      `export const DEFAULT_COLOR_SCHEME = '${defaultMode}' as const;`,
      '',
    ].join('\n'),
    'utf8',
  );

  console.log(`[theme] applied ${theme} (default: ${defaultMode})`);
}

const opts = parseArgs(process.argv.slice(2));
ensureThemesRepo();
copyWebTheme(opts.theme, opts.defaultMode);
